Modificado ciertos elementos para hacer funcionar el ng-build
src/app/editar-bodegas/editar-bodegas.component.html(30,41): Property 'nuevo_sede' does not exist on type 'EditarBo
degasComponent'. Did you mean 'nuevo_sedes'?
src/app/ver-inventario/ver-inventario.component.html(16,43): Property 'buscar' does not exist on type 'VerInventari
oComponent'.